jdbc:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/butler?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mysql
server:
  port: 8101
#  context-path: /origin-provider
spring:
  application:
    name: origin-provider
#logging:                                # 配置日志级别，让hibernate打印出执行的SQL
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true